//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextBasedRPGGame.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnemyModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Healthpoints { get; set; }
        public Nullable<int> Current_healthpoints { get; set; }
        public int Vit { get; set; }
        public int Dex { get; set; }
        public int STR { get; set; }
        public int ACC { get; set; }
        public Nullable<int> Exp_Gain { get; set; }
        public Nullable<int> EnLevel { get; set; }
        public Nullable<int> Money_Gain { get; set; }
        public Nullable<int> Place_Id { get; set; }
    }
}
