//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextBasedRPGGame.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> HealthPoints { get; set; }
        public Nullable<int> Current_healthpoints { get; set; }
        public Nullable<int> Vit { get; set; }
        public Nullable<int> Dex { get; set; }
        public Nullable<int> Str { get; set; }
        public Nullable<int> Acc { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<int> Char_level { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> Current_place { get; set; }
        public Nullable<int> Equiped_weapon_id { get; set; }
        public Nullable<int> Equiped_Armor_id { get; set; }
    }
}
