//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextBasedRPGGame.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PlaceModel
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Bed { get; set; }
        public Nullable<bool> Forge { get; set; }
        public Nullable<bool> Shop { get; set; }
        public Nullable<bool> Arena { get; set; }
        public Nullable<int> Next_Place { get; set; }
        public Nullable<int> Prev_Place { get; set; }
    }
}
